dataDirectory: /tmp/cvio-db

uriPrefix: http://127.0.0.1:8080/api

elasticsearchBindHost: 127.0.0.1

elasticsearchEnableHttp: true



####################################
## Dropwizard options (some of them)             
## For more options take a look at:
## http://dropwizard.codahale.com/manual/core/#configuration-defaults

# HTTP-specific options.
http:
  # The port on which the HTTP server listens for service requests.
  # Because Java cannot drop privileges in a POSIX system, these
  # ports cannot be in the range 1-1024. A port value of 0 will
  # make the OS use an arbitrary unused port.
  port: 8080

  # The port on which the HTTP server listens for administrative
  # requests. Subject to the same limitations as "port". If this is
  # set to the same value as port, the admin routes will be mounted
  # under /admin.
  adminPort: 8081

  # The hostname of the interface to which the HTTP server socket
  # will be bound. If omitted, the socket will listen on all
  # interfaces.
  # bindHost: null

  # If specified, adds Basic Authentication to the admin port using
  # this username.
  # adminUsername: null

  # If specified, adds Basic Authentication to the admin port using
  # this password. (Requires adminUsername to be specified).
  # adminPassword: null

  # The root path for the Jersey servlet.
  rootPath: "/api/*"

  # SSL configuration parameters. If omitted, all of these parameters
  # will fall back to using JVM-specific defaults (except for
  # supportedProtocols).
  #ssl:

    # The path to the Java Keystore which contains the server's SSL
    # certificate.
    #keyStore: /path/to/keystore

    # The password for the keystore.
    #keyStorePassword: "password"

    # The password for the key manager.
    #keyManagerPassword: "password"

    # The keystore type.
    #keyStoreType: JKS

    # If the trust store is a separate file, the path to the Java
    # keystore which contains certificates for the validation of
    # clients.
    #trustStore: /path/to/truststore

    # The password for the trust store.
    #trustStorePassword: "password"

    # The keystore type for the trust store.
    #trustStoreType: JKS

    # Whether or not to require authentication by peer certificate.
    #needClientAuth: true

    # Whether or not to prompt clients for their peer certificates.
    #wantClientAuth: true

    # The alias of the certificate to use for SSL.
    #certAlias: "cert"

    # If true, allows clients to renegotiate.
    #
    # ONLY ALLOW CLIENTS TO RENEGOTIATE IF YOUR JVM HAS A FIX FOR
    # CVE-2009-3555. DOING OTHERWISE WILL MAKE YOUR SERVICE VULNERABLE
    # TO SSL RENEGOTIATION ATTACKS.
    #allowRenegotiate: false

    # The path to the Certificate Revocation List.
    #crlPath: /path/to/revocation-list

    # Whether or not to enable Certificate Revocation List
    # Distribution Points support.
    #crldpEnabled: true

    # Whether or not to enable On-Line Certificate Status Protocol
    # support.
    #ocspEnabled: true

    # The OCSP Responder URL.
    #ocspResponderUrl: "http://blah"

    # The maximum length of a valid certificate verification path.
    #maxCertPathLength: 1

    # Whether or not peer certificates should be validated. Only
    # valid for PKIX trust stores.
    #validatePeers: true

    # The name of the JCE provider to use for SSL.
    #jceProvider: "SUN"

    # The list of supported SSL/TLS protocols. Dropwizard
    # intentionally disables SSLv2Hello for security reasons.
    #supportedProtocols: ["SSLv3", "TLSv1", "TLSv1.1", "TLSv1.2"]

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO,
  # DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    org.tarent.cvio.server: TRACE


