#!/bin/sh
# postinst script for cvio


mkdir -p /var/lib/cvio/data
chmod 0700 /var/lib/cvio/data
chmod 0600 /etc/cvio/config.yaml

## ensure the daemontools scan service is running
pgrep svscan || initctl reload-configuration
pgrep svscan || initctl start svscan

update-service --add /etc/cvio/cvio cvio

initctl reload svscan

#DEBHELPER#

exit 0
