#!/bin/sh
# postinst script for cvio

## ensure the daemontools scan service is running
pgrep svscan || initctl reload-configuration
pgrep svscan || initctl start svscan


update-service --add /etc/cvio/cvio cvio

initctl reload svscan

#DEBHELPER#

exit 0
